site_name: 'WP-WebAuthn Documentation'
site_description: 'WP-WebAuthn English Documentation'
site_author: 'Axton'
site_url: 'https://doc.flyhigher.top/wp-webauthn/en-US/'

# Repository
repo_name: 'yrccondor/wp-webauthn'
repo_url: 'https://github.com/yrccondor/wp-webauthn'
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 AxtonYao'

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo: 'img/logo.png'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  include_search_page: false
  search_index_only: true

plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/yrccondor/wp-webauthn'
    - type: 'home'
      link: 'https://doc.flyhigher.top'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - WP-Webauthn Doc: index.md
  - WebAuthn: webauthn.md
  - Installation & Configuration: config.md
  - Shortcodes:
    - Login Form: shortcodes/login_form.md
    - Register Form: shortcodes/register_form.md
    - Verify Button: shortcodes/verify_button.md
    - Authenticator List: shortcodes/list.md
  - FAQ: faq.md
  - Languages:
    - 简体中文: 'https://doc.flyhigher.top/wp-webauthn/zh-CN/'
    - English: 'https://doc.flyhigher.top/wp-webauthn/en-US/'